### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Beltrano",
    "email": "beltran2@gmail.com",
    "password": "abc123"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "beltran2@gmail.com",
    "password": "abc123"
}

### 3) Get users
GET http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI0ZjkzZGQ1LWU2NTgtNGIwZS05ZWZmLWIyNjYwMjBkZTZiOCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk1MzQ5NzQsImV4cCI6MTY1OTYyMTM3NH0.E3nB9HTT3Pl3sMsc8U49ISPxx2uKGFv6oQ6R7f88iws

### 3) Delete user
DELETE http://localhost:3003/users/e7513995-709c-498b-9f97-6a2fcc941342
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxNzNhYWM0LTc1NTktNDgzNi1hNDYzLTE4ZGUwZTdmZTlhNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM2MzA4ODgsImV4cCI6MTY2MzcxNzI4OH0.676z7qWbXkxALIDhc5N_CkgMoswq-NMPgIgaqj8w9_k