### Ping
GET http://localhost:3003/ping

### Create
POST http://localhost:3003/users/create
Content-Type: application/json

{
    "firstName": "alice",
    "lastName": "alice@gmail.com",
    "participation": 20
}

### getAllUsers
GET http://localhost:3003/users/getAllUsers
Content-Type: application/json
